# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/bus_booking_db
spring.datasource.username=postgres
spring.datasource.password=221902149

# JPA / Hibernate Properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JSON Integration (For JSONB fields like audit_logs, payments)
spring.jackson.serialization.fail-on-empty-beans=false