# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/bus_booking_db
spring.datasource.username=postgres
spring.datasource.password=221902149

# JPA / Hibernate Properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JSON Integration (For JSONB fields like audit_logs, payments)
spring.jackson.serialization.fail-on-empty-beans=false


stripe.api.key=sk_test_...
stripe.webhook.secret=whsec_...
stripe.success.url=https://yourdomain.com
stripe.cancel.url=https://yourdomain.com

spring.task.execution.pool.core-size=5
spring.task.execution.pool.max-size=20
spring.task.execution.pool.queue-capacity=500

#Hibernate multiple INSERT কোয়েরিকে মার্চ করে একক ব্যাচ কোয়েরি আকারে ডাটাবেজে পাঠাবে।
spring.jpa.properties.hibernate.jdbc.batch_size=20
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
